// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIrXOUeJmdqJF-0u356DqTcY4ZFdgaKag',
    appId: '1:601824604740:android:d9f70a4e19b2dbc07e8211',
    messagingSenderId: '601824604740',
    projectId: 'food2go-7c5b1',
    storageBucket: 'food2go-7c5b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR_U_E4tF2hkhihYlBUfaU1Rbbhf-CEBI',
    appId: '1:601824604740:ios:8e56cd53f11b5fff7e8211',
    messagingSenderId: '601824604740',
    projectId: 'food2go-7c5b1',
    storageBucket: 'food2go-7c5b1.firebasestorage.app',
    iosBundleId: 'com.app.sultan',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCreBBY-Xq0WcNy4Y7VCQYnrBbYlfd2ooQ',
    appId: '1:601824604740:web:ff3d24f7053eced67e8211',
    messagingSenderId: '601824604740',
    projectId: 'food2go-7c5b1',
    authDomain: 'food2go-7c5b1.firebaseapp.com',
    storageBucket: 'food2go-7c5b1.firebasestorage.app',
  );

}